#!/usr/bin/env node
// AI: below section was generated by an AI
//
// Signs a glowline OTA firmware image and writes the manifest the backend's /admin/firmware upload
// expects: { version, size, sha256, keyId, signature }. Ported from glowline-app's
// tools/sign-release.js (same signed payload, same DER signature encoding), with the private key
// located via $LUMEN_OTA_KEY_DIR instead of an arbitrary --key path.
//
// Usage:
//   LUMEN_OTA_KEY_DIR=<dir> node tools/sign-release.mjs \
//     --bin <firmware.bin> --version <x.y.z> --keyFile <name.pem> [--keyId primary|spare] [--out <manifest.json>]
//
// --keyFile is a bare filename inside $LUMEN_OTA_KEY_DIR (no directories), so no local path or key
// filename ever needs to live in this public repo.
//
// Safety properties:
// - Never prints, logs or copies key material. Errors from key parsing are reported by code only.
// - Refuses a key file whose permissions are wider than 0600.
// - Before writing anything, verifies the new signature against the public key embedded in
//   usermods/glowline/glowline.cpp for the same keyId -- the exact check the device performs
//   (verifyManifestSignature()). A private key that doesn't match the firmware's frozen public key
//   is caught here instead of as a refused update on a device.
// - The manifest is written next to the binary by default (docs/OTA.md Section 6).

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { createHash, createPrivateKey, createPublicKey, sign, verify } from 'node:crypto';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const USAGE = 'Usage: LUMEN_OTA_KEY_DIR=<dir> node tools/sign-release.mjs --bin <firmware.bin> --version <x.y.z> --keyFile <name.pem> [--keyId primary|spare] [--out <manifest.json>]';

function fail(msg) {
  console.error(`sign-release: ${msg}`);
  process.exit(1);
}

// --name value pairs only; anything else is a usage error rather than silently ignored.
const args = new Map();
for (let i = 2; i < process.argv.length; i += 2) {
  const flag = process.argv[i];
  const value = process.argv[i + 1];
  if (!flag.startsWith('--') || value === undefined) fail(USAGE);
  args.set(flag.slice(2), value);
}

const binPath = args.get('bin');
const version = args.get('version');
const keyFile = args.get('keyFile');
const keyId = args.get('keyId') ?? 'primary';
if (!binPath || !version || !keyFile) fail(USAGE);
const outPath = args.get('out') ?? join(dirname(binPath), 'manifest.json');

// The firmware only knows these two keyIds (glowline.cpp selectOtaKey()).
if (keyId !== 'primary' && keyId !== 'spare') fail(`--keyId must be "primary" or "spare", got "${keyId}"`);

// The signed payload is newline-delimited, so a newline (or any control/non-ASCII char) inside the
// version would make the signed bytes ambiguous. Keep versions to plain printable ASCII.
if (!/^[\x21-\x7e]+$/.test(version)) fail('--version must be non-empty printable ASCII without spaces');

// --- Locate the key strictly inside $LUMEN_OTA_KEY_DIR ---
const keyDir = process.env.LUMEN_OTA_KEY_DIR;
if (!keyDir) fail('LUMEN_OTA_KEY_DIR is not set');
if (!isAbsolute(keyDir)) fail('LUMEN_OTA_KEY_DIR must be an absolute path');
let keyDirStat;
try { keyDirStat = statSync(keyDir); } catch { fail('LUMEN_OTA_KEY_DIR does not exist'); }
if (!keyDirStat.isDirectory()) fail('LUMEN_OTA_KEY_DIR is not a directory');

if (keyFile !== basename(keyFile) || keyFile === '.' || keyFile === '..') {
  fail('--keyFile must be a bare filename inside LUMEN_OTA_KEY_DIR (no directories)');
}
const keyPath = join(keyDir, keyFile);
let keyStat;
try { keyStat = statSync(keyPath); } catch { fail(`key file "${keyFile}" not found in LUMEN_OTA_KEY_DIR`); }
if (!keyStat.isFile()) fail(`key file "${keyFile}" is not a regular file`);
// "Wider than 600": any group/other bit, or owner execute.
const mode = keyStat.mode & 0o777;
if (mode & 0o177) fail(`key file "${keyFile}" has permissions ${mode.toString(8).padStart(3, '0')}; must be 600 or stricter (chmod 600)`);

// --- Hash the image ---
let bytes;
try { bytes = readFileSync(binPath); } catch { fail(`cannot read --bin "${binPath}"`); }
if (bytes.length === 0) fail('--bin is empty');
// ESP app images start with magic byte 0xE9 (ESP-IDF esp_app_format.h, ESP_IMAGE_HEADER_MAGIC) --
// cheap guard against signing some unrelated file.
if (bytes[0] !== 0xe9) fail('--bin does not start with the ESP image magic byte 0xE9; is this really firmware.bin?');
const size = bytes.length;
const sha256 = createHash('sha256').update(bytes).digest('hex');

// Must match glowline.cpp verifyManifestSignature() and docs/OTA.md Section 3 byte-for-byte.
const signedBytes = Buffer.from(`${version}\n${size}\n${sha256}\n${keyId}`, 'utf8');

// --- Sign (key material stays inside this block and is never printed) ---
let signature;
try {
  const privateKey = createPrivateKey(readFileSync(keyPath));
  if (privateKey.asymmetricKeyType !== 'ec' || privateKey.asymmetricKeyDetails?.namedCurve !== 'prime256v1') {
    fail(`key file "${keyFile}" is not an EC P-256 (prime256v1) private key`);
  }
  // Default DER encoding: what mbedtls_pk_verify() on the device expects.
  signature = sign('sha256', signedBytes, privateKey).toString('base64');
} catch (err) {
  fail(`could not load or use key file "${keyFile}" (${err.code ?? 'unknown error'})`);
}

// --- Self-check against the public key the firmware actually embeds ---
const scriptDir = dirname(fileURLToPath(import.meta.url));
const firmwareSrc = resolve(scriptDir, '..', 'usermods', 'glowline', 'glowline.cpp');
const embeddedPem = readEmbeddedPublicKey(firmwareSrc, keyId === 'primary' ? 'kOtaKeyPrimary' : 'kOtaKeySpare');
const ok = verify('sha256', signedBytes, createPublicKey(embeddedPem), Buffer.from(signature, 'base64'));
if (!ok) fail(`signature does NOT verify against the "${keyId}" public key embedded in glowline.cpp -- wrong key file for this keyId? Nothing written.`);

const manifest = { version, size, sha256, keyId, signature };
writeFileSync(outPath, JSON.stringify(manifest, null, 2) + '\n');

console.log(`Verified against embedded "${keyId}" public key (glowline.cpp).`);
console.log(`Wrote ${outPath}`);
console.log(manifest);

// Extracts a PEM from a C++ declaration of the form
//   static constexpr const char* <name> =
//     "-----BEGIN PUBLIC KEY-----\n"
//     "...\n"
//     "-----END PUBLIC KEY-----\n";
// by concatenating the string literals up to the terminating semicolon and unescaping "\n".
function readEmbeddedPublicKey(srcPath, constName) {
  let src;
  try { src = readFileSync(srcPath, 'utf8'); } catch { fail(`cannot read ${srcPath} to self-check the signature`); }
  const start = src.indexOf(`${constName} =`);
  if (start < 0) fail(`${constName} not found in ${srcPath}`);
  const end = src.indexOf(';', start);
  const literals = [...src.slice(start, end).matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => m[1]);
  const pem = literals.join('').replace(/\\n/g, '\n');
  if (!pem.includes('BEGIN PUBLIC KEY')) fail(`${constName} in ${srcPath} doesn't look like a PEM public key`);
  return pem;
}
// AI: end
